# Generated by Django 3.2.8 on 2021-10-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0008_alter_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.IntegerField(max_length=12),
        ),
    ]
